
#DATOS PARA LA CONEXION A LAS BASES DE DATOS(BASE DE DATOS Y BODEGA)


# CONEXION A LA BASE DE DATOS 
ADVENTURE_WORKS_DB: #NOMBRE DE BASE DE DATOS (SIMPLEMENTE NOMBRE IDENTIFICADOR)
  drivername: ODBC Driver 17 for SQL Server
  dbname: AdventureWorks2022   #NOMBRE DE LA BASE DE DATOS EN POSTGRES
  user: sa
  password: 1234
  host: DANGERPC\\SQLEXPRESS
  port: 1433

ADVENTURE_WORKS_DW: #NOMBRE DE BASE DE DATOS (SIMPLEMENTE NOMBRE IDENTIFICADOR)
  drivername: ODBC Driver 17 for SQL Server
  dbname: AdventureWorksDW   #NOMBRE DE LA BASE DE DATOS (BODEGA) EN POSTGRES
  user: sa
  password: 1234
  host: DANGERPC\\SQLEXPRESS
  port: 1433


#PARA PERMITIR QUE CARGUE LAS DIMENSIONES
CARGAR_DIMENSIONES:
  True
